Use GitHub actions
rayyansys/rayyan-formats pull request #17
Opened 2022-07-15 23:09 UTC by kohrVid

Closes #16.

This PR replaces our Travis CI configuration with a Github Action workflow. The workflow has been set up to run rspec tests with the following rubies:

* 2.3 - failing
* 2.4 - failing
* 2.5 - failing
* 2.6 - failing
* 2.7 - failing

An example of the CI job can be found on my fork of this repo [here](https://github.com/kohrVid/rayyan-formats/runs/7365684599?check_suite_focus=true). Note, this workflow often fails with a 422 error, suggesting that the repo will need to be removed and re-added to coveralls.io.

2022-07-18 20:37 UTC, hammady requested changes

2022-07-19 17:53 UTC, hammady commented on Gemfile.lock
> +    docile (1.1.5)
This was downgraded.

2022-07-19 17:54 UTC, hammady commented on Gemfile.lock
> +    simplecov (0.14.1)
Downgraded.

2022-07-19 20:26 UTC, hammady commented on README.md
> +![Build Status](https://github.com/rayyansys/rayyan-formats/actions/workflows/ruby_2.3.yml/badge.svg)
Is this correct?

2022-07-20 13:05 UTC, kohrVid commented on README.md
> +![Build Status](https://github.com/rayyansys/rayyan-formats/actions/workflows/ruby_2.3.yml/badge.svg)
Sorry - that's from the old workflow I think. Have updated the PR with the correct URL

2022-07-20 16:51 UTC, merged